import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';

const TEST_DIR = path.join(os.tmpdir(), 'soloknuckle-test-ai-watcher');
let execSyncMock: ReturnType<typeof vi.fn>;

vi.mock('child_process', () => ({
  execSync: (...args: unknown[]) => execSyncMock(...args),
}));

vi.mock('../cli/scanner', () => ({
  scanDiffForSecretsAndPII: vi.fn(() => []),
}));

describe('AI Commit Watcher', () => {
  beforeEach(() => {
    fs.mkdirSync(TEST_DIR, { recursive: true });
    vi.spyOn(process, 'cwd').mockReturnValue(TEST_DIR);
    execSyncMock = vi.fn();
    const watcherFile = path.join(TEST_DIR, '.soloknuckle', 'ai-watcher.json');
    if (fs.existsSync(watcherFile)) fs.unlinkSync(watcherFile);
  });

  afterEach(() => {
    fs.rmSync(TEST_DIR, { recursive: true, force: true });
    vi.restoreAllMocks();
    vi.resetModules();
  });

  describe('isAICommit', () => {
    it('detects Copilot commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('Co-authored-by: Copilot <copilot@github.com>')).toBe(true);
    });

    it('detects Claude commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('Co-authored-by: Claude <claude@anthropic.com>')).toBe(true);
    });

    it('detects GPT commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('Co-authored-by: GPT <gpt@openai.com>')).toBe(true);
    });

    it('detects Cursor commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('fix: cursor generated code')).toBe(true);
    });

    it('detects Windsurf commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('refactor: windsurf optimization')).toBe(true);
    });

    it('detects Anthropic commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('feat: anthropic model integration')).toBe(true);
    });

    it('detects OpenAI commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('chore: openai api update')).toBe(true);
    });

    it('detects AI-generated commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('generated by ai')).toBe(true);
      expect(isAICommit('AI-generated patch')).toBe(true);
    });

    it('detects automated commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('automated commit from bot')).toBe(true);
    });

    it('returns false for human commits', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('fix: resolve null pointer in handler')).toBe(false);
      expect(isAICommit('feat: add user authentication')).toBe(false);
      expect(isAICommit('chore: update dependencies')).toBe(false);
    });

    it('is case-insensitive', async () => {
      const { isAICommit } = await import('../cli/ai-watcher');
      expect(isAICommit('co-authored-by: copilot <copilot@github.com>')).toBe(true);
      expect(isAICommit('Co-Authored-By: Claude <claude@anthropic.com>')).toBe(true);
    });
  });

  describe('loadWatcherData', () => {
    it('creates fresh data when no file exists', async () => {
      const { loadWatcherData } = await import('../cli/ai-watcher');
      const data = loadWatcherData();
      expect(data.totalCommits).toBe(0);
      expect(data.aiCommits).toBe(0);
      expect(data.humanCommits).toBe(0);
      expect(data.records).toHaveLength(0);
    });

    it('loads existing watcher data', async () => {
      const { loadWatcherData, saveWatcherData } = await import('../cli/ai-watcher');
      const data = loadWatcherData();
      data.totalCommits = 10;
      data.aiCommits = 3;
      data.humanCommits = 7;
      data.acceptanceRate = 100;
      data.quarantineRate = 0;
      saveWatcherData(data);

      const loaded = loadWatcherData();
      expect(loaded.totalCommits).toBe(10);
      expect(loaded.aiCommits).toBe(3);
      expect(loaded.humanCommits).toBe(7);
    });

    it('returns fresh data on corrupted file', async () => {
      const watcherFile = path.join(TEST_DIR, '.soloknuckle', 'ai-watcher.json');
      fs.mkdirSync(path.join(TEST_DIR, '.soloknuckle'), { recursive: true });
      fs.writeFileSync(watcherFile, 'not valid json');

      const { loadWatcherData } = await import('../cli/ai-watcher');
      const data = loadWatcherData();
      expect(data.totalCommits).toBe(0);
    });
  });

  describe('saveWatcherData', () => {
    it('creates .soloknuckle directory if it does not exist', async () => {
      const { saveWatcherData, loadWatcherData } = await import('../cli/ai-watcher');
      const data = loadWatcherData();
      data.totalCommits = 5;
      saveWatcherData(data);

      const watcherFile = path.join(TEST_DIR, '.soloknuckle', 'ai-watcher.json');
      expect(fs.existsSync(watcherFile)).toBe(true);
      const saved = JSON.parse(fs.readFileSync(watcherFile, 'utf-8'));
      expect(saved.totalCommits).toBe(5);
    });
  });

  describe('getWatcherSummary', () => {
    it('returns summary string', async () => {
      const { getWatcherSummary, saveWatcherData, loadWatcherData } = await import('../cli/ai-watcher');
      const data = loadWatcherData();
      data.totalCommits = 10;
      data.aiCommits = 3;
      data.humanCommits = 7;
      data.acceptanceRate = 80;
      data.quarantineRate = 20;
      saveWatcherData(data);

      const summary = getWatcherSummary();
      expect(summary).toContain('Total commits tracked: 10');
      expect(summary).toContain('AI commits: 3');
      expect(summary).toContain('Human commits: 7');
      expect(summary).toContain('AI acceptance rate: 80%');
      expect(summary).toContain('AI quarantine rate: 20%');
    });
  });

  describe('classifyCommit', () => {
    it('flags AI signature commits as AI with high confidence', async () => {
      const { classifyCommit } = await import('../cli/ai-watcher');
      const result = classifyCommit('Co-authored-by: Copilot <copilot@github.com>', 'humandev@example.com');
      expect(result.isAi).toBe(true);
      expect(result.confidence).toBe('high');
      expect(result.score).toBe(4); // +4 signature, git config user.email mock returns '' so no -3
    });

    it('flags human commits as non-AI', async () => {
      const { classifyCommit } = await import('../cli/ai-watcher');
      const result = classifyCommit('fix: resolve null pointer in handler', 'humandev@example.com');
      expect(result.isAi).toBe(false);
      expect(result.confidence).toBe('low');
    });

    it('treats bot-like author emails as AI signal', async () => {
      const { classifyCommit } = await import('../cli/ai-watcher');
      const result = classifyCommit('chore: bump deps', 'renovate[bot]@users.noreply.github.com');
      expect(result.isAi).toBe(true);
      expect(result.score).toBe(3);
    });
  });

  describe('markCommit', () => {
    it('writes an override file and recomputes rates for tracked records', async () => {
      const { markCommit, loadWatcherData, saveWatcherData, loadOverrides } = await import('../cli/ai-watcher');
      const data = loadWatcherData();
      data.records.push({
        sha: 'face000000000000000000000000000000000000',
        message: 'Co-authored-by: Copilot',
        timestamp: new Date().toISOString(),
        isAi: true,
        diffStats: { files: 1, additions: 1, deletions: 0 },
        scanResult: { passed: true, violations: [] },
        branchAction: { action: 'passed', branch: 'ai-approved/face0000' },
      });
      data.records.push({
        sha: 'beeef00000000000000000000000000000000000',
        message: 'fix: human work',
        timestamp: new Date().toISOString(),
        isAi: false,
        diffStats: { files: 1, additions: 1, deletions: 0 },
        scanResult: { passed: true, violations: [] },
        branchAction: { action: 'skipped' },
      });
      data.totalCommits = 2;
      data.aiCommits = 1;
      data.humanCommits = 1;
      saveWatcherData(data);

      const result = markCommit('face000000000000000000000000000000000000', 'human');
      expect(result.success).toBe(true);

      const overrides = loadOverrides();
      expect(overrides['face000000000000000000000000000000000000']).toBe('human');

      const updated = loadWatcherData();
      expect(updated.records[0].isAi).toBe(false);
      expect(updated.aiCommits).toBe(0);
      expect(updated.humanCommits).toBe(2);
      expect(updated.acceptanceRate).toBe(0);
    });
  });

  describe('watchCommit', () => {
    it('returns error for invalid sha', async () => {
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git log -1 --format=%s invalid-sha')) throw new Error('bad rev');
        return '';
      });
      const { watchCommit } = await import('../cli/ai-watcher');
      const result = watchCommit('invalid-sha');
      expect(result.success).toBe(false);
      expect(result.message).toContain('Could not read commit');
    });

    it('returns error when not a git repo (HEAD fails)', async () => {
      execSyncMock.mockImplementation(() => { throw new Error('not a git repo'); });
      const { watchCommit } = await import('../cli/ai-watcher');
      const result = watchCommit();
      expect(result.success).toBe(false);
      expect(result.message).toContain('Not a git repository');
    });

    it('watches a human commit successfully', async () => {
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git rev-parse HEAD')) return 'abc123def456\n';
        if (cmd.includes('git log -1 --format=%s')) return 'fix: resolve bug\n';
        if (cmd.includes('git diff --numstat')) return '1\t2\tfile.ts\n';
        if (cmd.includes('git diff')) return '+old\n-new\n';
        return '';
      });
      const { watchCommit } = await import('../cli/ai-watcher');
      const result = watchCommit();
      expect(result.success).toBe(true);
      expect(result.record.isAi).toBe(false);
      expect(result.record.sha).toBe('abc123def456');
      expect(result.record.message).toBe('fix: resolve bug');
      expect(result.record.branchAction.action).toBe('skipped');
    });

    it('watches a passing AI commit and creates branch', async () => {
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git rev-parse HEAD')) return 'aabb11223344\n';
        if (cmd.includes('git log -1 --format=%s')) return 'Co-authored-by: Copilot\n';
        if (cmd.includes('git diff --numstat')) return '3\t1\tindex.ts\n';
        if (cmd.includes('git diff')) return '+safe code\n';
        if (cmd.includes('git branch ai-approved/')) return '';
        return '';
      });
      const { watchCommit } = await import('../cli/ai-watcher');
      const result = watchCommit();
      expect(result.success).toBe(true);
      expect(result.record.isAi).toBe(true);
      expect(result.record.branchAction.action).toBe('passed');
      expect(result.record.branchAction.branch).toBe('ai-approved/aabb1122');
      expect(result.message).toContain('approved');
    });

    it('returns already-watched record for duplicate sha', async () => {
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git rev-parse HEAD')) return 'deadbeef1234\n';
        if (cmd.includes('git log -1 --format=%s')) return 'fix: stuff\n';
        return '';
      });
      const { watchCommit } = await import('../cli/ai-watcher');
      const first = watchCommit();
      expect(first.success).toBe(true);
      const second = watchCommit();
      expect(second.success).toBe(true);
      expect(second.message).toContain('already watched');
    });

    it('handles first commit (no parent diff)', async () => {
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git rev-parse HEAD')) return 'first11111111\n';
        if (cmd.includes('git log -1 --format=%s')) return 'initial commit\n';
        if (cmd.includes('git diff')) throw new Error('no parent');
        return '';
      });
      const { watchCommit } = await import('../cli/ai-watcher');
      const result = watchCommit();
      expect(result.success).toBe(true);
      expect(result.record.diffStats.files).toBe(0);
    });

    it('handles branch creation failure gracefully', async () => {
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git rev-parse HEAD')) return 'fail11111111\n';
        if (cmd.includes('git log -1 --format=%s')) return 'Co-authored-by: GPT\n';
        if (cmd.includes('git diff --numstat')) return '1\t1\tfile.ts\n';
        if (cmd.includes('git diff')) return '+ok\n';
        if (cmd.includes('git branch ai-approved/')) throw new Error('branch exists');
        return '';
      });
      const { watchCommit } = await import('../cli/ai-watcher');
      const result = watchCommit();
      expect(result.success).toBe(true);
      expect(result.record.branchAction.action).toBe('passed');
      expect(result.record.branchAction.reason).toContain('Branch creation failed');
    });
  });

  describe('watchRecentCommits', () => {
    it('watches last N commits', async () => {
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git log --oneline')) return 'sha1\nsha2\nsha3\n';
        if (cmd.includes('git log -1 --format=%s sha1')) return 'commit 1\n';
        if (cmd.includes('git log -1 --format=%s sha2')) return 'commit 2\n';
        if (cmd.includes('git log -1 --format=%s sha3')) return 'commit 3\n';
        return '';
      });
      const { watchRecentCommits } = await import('../cli/ai-watcher');
      const results = watchRecentCommits(3);
      expect(results).toHaveLength(3);
    });

    it('returns empty array when not a git repo', async () => {
      execSyncMock.mockImplementation(() => { throw new Error('not a git repo'); });
      const { watchRecentCommits } = await import('../cli/ai-watcher');
      const results = watchRecentCommits();
      expect(results).toHaveLength(0);
    });

    it('defaults to 10 commits', async () => {
      const shas = Array.from({ length: 10 }, (_, i) => `sha${i}`);
      execSyncMock.mockImplementation((cmd: string) => {
        if (cmd.includes('git log --oneline')) return shas.join('\n') + '\n';
        return 'human commit\n';
      });
      const { watchRecentCommits } = await import('../cli/ai-watcher');
      const results = watchRecentCommits();
      expect(results).toHaveLength(10);
    });
  });
});
